# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 09db3cd5c3c67e337725620d66cff6266e4e20ec76dcb8e9e8a362894133b82c628e491e59d9d1229f9115abef8c9faa056f7d5c9d0b5bfafbbdb179e22da200

test:
  secret_key_base: 2732ca835ae247090496573b39c87d77f7b64acfe7d9f07be41c211bc9165b0c9d660630e3ac4fc7d14dc50e34b34d559e3471f5aa95366c515f47875c12fcad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
